alias part1="cd \"Deel 1 - Lineaire Algebra\""
alias run11="python3 Opdr1LinAlg.py"
alias run12="python3 Opdr2LinAlg.py"
alias run13="python3 Opdr3LinAlg.py"
alias run14="python3 Opdr4LinAlg.py"
alias run15="python3 Opdr5LinAlg.py"
alias runp1="python3 FitnessFunctionTest.py"
